Changes in the attestation flow.
ElrondNetwork/sc-attestation-rs pull request #14
Opened 2021-01-05 14:49 UTC by andrei-marinica

Renamed 2 of the main endpoints and changed who can call them and when.

2021-01-05 15:01 UTC, dorin-iancu approved these changes

2021-01-05 15:01 UTC, dorin-iancu commented on src/lib.rs
> +			"registraction not started for user"
registraction -> registration

2021-01-06 07:48 UTC, sasurobert commented on src/lib.rs
> +			"registraction not started for user"
+1

2021-01-06 08:01 UTC, sasurobert requested changes
good job - only that typo

2021-01-06 08:14 UTC, dorin-iancu approved these changes

2021-01-06 08:14 UTC, sasurobert approved these changes

2021-01-06 08:15 UTC, merged