Attestation c
ElrondNetwork/sc-attestation-rs pull request #8
Opened 2020-11-17 15:33 UTC by dorin-iancu

2020-11-17 16:36 UTC, andrei-marinica requested changes

2020-11-17 16:36 UTC, andrei-marinica commented on c-version/storage.c
> +    int64storageStore(TOTAL_ATTESTATORS_KEY, TOTAL_ATTESTATORS_KEY_LEN, len);
int64storageStore is deprecated
use smallIntStorageStoreUnsigned instead

2020-11-17 16:36 UTC, andrei-marinica commented on c-version/storage.c
> +    return int64storageLoad(TOTAL_ATTESTATORS_KEY, TOTAL_ATTESTATORS_KEY_LEN);
int64storageLoad is deprecated
use smallIntStorageLoadUnsigned instead

2020-11-17 16:36 UTC, andrei-marinica commented on c-version/elrond/context.h
> +long long int64getArgument(int argumentIndex);
int64getArgument is deprecated
use smallIntGetUnsignedArgument instead (or smallIntGetSignedArgument, but I don't think you need signed numbers anywhere in the contract)

2020-11-17 16:36 UTC, andrei-marinica commented on c-version/elrond/context.h
> +long long int64storageLoad(const byte *key, int keyLength);
int64storageStore and int64storageLoad are deprecated, we should remove them from here from all contracts

I'm posting here the small int EI from arwen:

// extern long long smallIntGetUnsignedArgument(void *context, int32_t id);
// extern long long smallIntGetSignedArgument(void *context, int32_t id);
//
// extern void smallIntFinishUnsigned(void* context, long long value);
// extern void smallIntFinishSigned(void* context, long long value);
//
// extern int32_t smallIntStorageStoreUnsigned(void *context, int32_t keyOffset, int32_t keyLength, long long value);
// extern int32_t smallIntStorageStoreSigned(void *context, int32_t keyOffset, int32_t keyLength, long long value);
// extern long long smallIntStorageLoadUnsigned(void *context, int32_t keyOffset, int32_t keyLength);
// extern long long smallIntStorageLoadSigned(void *context, int32_t keyOffset, int32_t keyLength);
//
// ... and 4 deprecated functions that we should no longer have in the headers

2020-11-24 15:01 UTC, sasurobert reviewed
Looks impressive!

2020-11-24 15:01 UTC, sasurobert commented on .gitignore
> +*.o
empty line to end of file

2020-11-24 15:01 UTC, sasurobert commented on c-version/helpers.c
> +// fake memset
these are not fake. these are the actual implementation :) delete comment.

2020-11-24 15:01 UTC, sasurobert commented on c-version/helpers.c
> +// fake memcpy
these are not fake. these are the actual implementation :) delete comment.

2020-11-25 08:21 UTC, sasurobert approved these changes

2020-11-25 11:59 UTC, sasurobert approved these changes

2020-11-25 11:59 UTC, merged